### ISSUE TITLE
Not using v.zero SDK

### ISSUE THREAD

**Issue by ayb** [solidusio/solidus_braintree#14]
Current implementation is posting credit card data directly back to the server

> Started PATCH "/checkout/update/payment" for 127.0.0.1 at 2016-02-08 05:56:54 -0500
> Processing by Spree::CheckoutController#update as HTML
>  Parameters: {"utf8"=>"✓",
> "authenticity_token"=>"KLjo/1QEPRso8DOuTXlcCVZPlDD3/BcIxuWTUzh+/HhpbDw0gCfDVnYRiCHK8u00oRJGxW0Mbx33o6B0AIjmgg==",
> "order"=>{"payments_attributes"=>[{"payment_method_id"=>"2"}], "coupon_code"=>""}, "payment_source"=>{"2"=>{"name"=>"Test
> User", "number"=>"[FILTERED]", "expiry"=>"11 / 17", "verification_value"=>"[FILTERED]",
> "address_attributes"=>{"firstname"=>"Test ", "lastname"=>"User", "company"=>"", "address1"=>"431 Test Ave", "address2"=>"",
> "city"=>"Testing", "country_id"=>"232", "state_id"=>"3561", "state_name"=>"", "zipcode"=>"10001", "phone"=>"212-111-1111",
> "alternative_phone"=>""}, "cc_type"=>"visa"}}, "state"=>"payment"}

v.zero SDK does not post back credit card data, just a payment method nonce:

> {"payment_method_nonce"=>"761e1fad-94a3-4737-add1-6cccf7ec1b8d"}

**Comment by mike-bourgeous** [comment]
I work on a large ecommerce site that is currently planning a move from Spree to Solidus.  We use add client-side encryption and tokenization on both checkout and admin.  If we reimplement this for Solidus, would these changes be useful/welcome in this gem?
