### ISSUE TITLE
Select an implementation for how to store non credit card data in Solidus

### ISSUE THREAD

**Issue by allisonlarson** [solidusio/solidus_braintree#3]
## Problem

Braintree v.zero supports up to 7 payment method types. Solidus's `Spree::Gateway` class assumes the payment source is a `Spree::CreditCard`. Only one of Braintree's payment method types maps to a `Spree::CreditCard`. We only know the payment method type at the time of `Spree::Payment` creation. 
## 1. Multiple Payment Methods

Create new `Spree::Gateway`s for each payment method type that Braintree supports (Paypal, CreditCard, Coinbase, ApplePay, etc.).  
### Pros
- Follows the `Spree::Gateway` convention
- Ability to treat payment methods specifically
- Easiest to reason about
### Cons
- Its a hack: They all are conceptually the same gateway
- Shared/Duplicated configuration
- Complicates client token generation
- Complicates attaching `payment_method_id`
## 2. Braintree Catch-all Class

Create a new payment source class named `BraintreeSource` that has one-to-one relationships to each payment method type. Each relationship is optional, as long as one is associated.
### Pros
- Allows use of a single payment method for all Braintree types
- One source abstraction
### Cons
- ~~Would break compatibility with `solidus_gateway`~~
- Double the polymorphism!
## 3. Repurpose CreditCard Class

Use `Spree::CreditCard` class as a catchall for all payment method types. (Put Paypal email in the name field, and leave everything else `nil`.)
### Pros
- Easy
- Currently works, as is
- No Solidus changes required
### Cons
- Hackiest solution, literally cannot get hackier
- It's a hack
- Hack
- PayPal is not a credit card
## 4. Payment Source Marshalling

Replace polymorphic `source` association on `Spree::Payment` with a text field and marshall the payment method data into JSON. It will have a `type` key such as `credit_card` or `paypal` and contain fields specific to that type.
### Pros
- Most flexible, supports any payment type, including future ones
- Easy to extend with any gateway
### Cons
- Hard to query
- Potentially lose having a class backed source
## ~~5. Skip `Spree::Gateway`, subclass `Spree::PaymentMethod`~~

Instead of trying to get Braintree fit into `Spree::Gateway`, go one level up, subclassing `Spree::PaymentMethod` and implement the Braintree Catch-all Class solution on top of this new payment method class.
### Pros
- Pros of Braintree Catch-all Class
- Maintain compatibility with `solidus_gateway` or anything that depends on `Spree::Gateway`
### Cons
- The Braintree gateway IS a gateway, conceptually it should inherit from `Spree::Gateway`
- Duplication of some code in `Spree::Gateway` and our new class.

**Comment by ayb** [comment]
@allisonlarson Just found this and wanted to ask if there was any news?  Can this extension support Paypal as well as Credit Cards now?

**Comment by jdar** [comment]
I am also very interested in supporting paypal in addition to credit cards. 

Additionally, let me suggest configuration links would be helpful, now that v.zero api is featured on Paypal website -- I think I am looking at the wrong documentation (on paypal site.)

**Comment by allisonlarson** [comment]
@ayb This extension does support Paypal and credit card, but due to the restriction of a payment gateway only having one source in Solidus, the Paypal payment info gets stored in `Spree::CreditCard`, where the `type` is Paypal, and there is a JSON field for holding on to additional information. I believe that re-examining the payment gateway/method system is somewhere on the roadmap for Solidus, to make that a little more intuitive, but don't quote me :)

**Comment by allisonlarson** [comment]
@jdar I'm not sure what you mean... V.Zero is through Braintree, which is where those docs for configuring should be. Is that what you mean?

**Comment by mamhoff** [comment]
Just FYI there's an open PR on spree (https://github.com/spree/spree/pull/6831) which essentially does option #1. We needed it for a European payment provider that also has lots of different payment methods, and it did allow for some easy-to-do special treatments for some sources. With inheritance we could actually do away with the "multiple configurations" drawback.

**Comment by elia** [comment]
Closing as v.zero is no longer current.
