### ISSUE TITLE
Use of undefined show_flash function in frontend

### ISSUE THREAD

**Issue by hectoregm** [solidusio/solidus_braintree#31]
We use show_flash function to print a message when the tokenization has an error, but show_flash
is only defined in Solidus backend.

https://github.com/solidusio/solidus_braintree/blob/e48b3af0002650589b3a270997e1144834ac1529/lib/assets/javascripts/spree/frontend/braintree/solidus_braintree.js#L40

Maybe change it to an alert ?

**Comment by elia** [comment]
Closing as v.zero is no longer current.
