### ISSUE TITLE
Confusion on solidus_paypal_braintree vs solidus_braintree

### ISSUE THREAD

**Issue by masonjeffreys** [solidusio/solidus_braintree#72]
Can someone explain the difference in roadmaps between this gem and https://github.com/solidusio/solidus_paypal_braintree ?

Solidus_paypal_braintree is linked from the solidus website and includes frontend integration for braintree, whereas apparently this gem does not. I'm just wondering which will be around for the long term...

**Comment by arturtr** [comment]
@masonjeffreys the current project is legacy
![image](https://user-images.githubusercontent.com/783678/95707927-4829d800-0c9e-11eb-9890-a3995c18dc8d.png)

**Comment by kennyadsl** [comment]
We merged the two projects, now only Solidus Braintree is supported, and 2.0 contains the code of Solidus Paypal Braintree. The old Solidus Braintree is on the `v1.x` branch.
