### ISSUE TITLE
3DS 2.0 / Javascript SDK v3 integration

### ISSUE THREAD

**Issue by hefan** [solidusio/solidus_braintree#84]
Isn't the new 3ds 2.0 with Javascript SDK v3 required from 14th September 2019 on?
Braintree keeps sending mails regarding this.
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3
Not sure if the mentioned fallback to 3ds v1 will always work.

Will this extension cover this?

**Comment by elia** [comment]
It's not covered as newer versions are covered by solidus_paypal_braintree, although we'll merge it in this repo soon (see #92).
