### ISSUE TITLE
Merge with `solidus_paypal_braintree`

### ISSUE THREAD

**Issue by elia** [solidusio/solidus_braintree#90]
## Premise

We have two braintree extensions for solidus, the newer one (solidus_paypal_braintree, SPB from now on) is called after the first integration that was available but later grew out of it and now encompasses multiple payment methods. The former (solidus_braintree, SB from now on) has a more sensible name, but is stuck in the past.

## What

We should merge both into different versions of SB, more specifically:

1. merge the history of SPB into the one of SB (add the remote for SPB then merge with a merge-strategy that discards all the old code)
2. update the namespace and allow people to choose the namespace for database table names
3. release a new major of SB
4. release a new major of SPB that is empty and only depends on the newly released SB, with a post-install message that suggests switching the dependency in the gemfile
5. archive the SPB repo

### Considerations

- using majors we clearly try to get the attention of the users upgrading and give them a fair chance at understanding what's going on
- going forward we'll have less confusion on what extension is the right one for your application
- users using a git dependency in their gemfile will still have the burden of checking commits or the changelog manually

/cc @chrean @kennyadsl

**Comment by kennyadsl** [comment]
What about the `SolidusPayPalBraintree` namespace and database tables? With this change we would prevent people from switching from the old to the new namespace, unless there's a big database migration.

**Comment by kennyadsl** [comment]
Closing this one, the action plan has been split into individual issues in the right repository
