### ISSUE TITLE
Update the SolidusPaypalBraintree namespace to SolidusBraintree

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus_braintree#96]
## Goal

We want to rename the SolidusPaypalBraintree namespace to SolidusBraintree to simplify the extension's name and avoid it being confused with SolidusPaypalCommercePlatform.

## Requirements

* [x] For backward compatibility, we also need to contextually allow people to choose the namespace for database table names, so that those who are using the `solidus_paypal_braintree_prefix` can still update to the latest version. 
* [x] We want to limit the manual changes that users of SolidusPaypalBraintree have to make in order to transition to SolidusBraintree. We may want to consider to alias the SolidusPaypalBraintree class and the solidus_paypal_braintree JS file names. The aliases have to be deprecated.
* [x] We want to ensure that existing payments to SolidusPaypalBraintree will work with the new name. We may want to add a data migration to rename the source type of these payments from SolidusPaypalBraintree to SolidusBraintree.

## Dependencies

This is blocked by #92.

**Comment by gsmendoza** [comment]
As discussed in the standup, we'll keep jQuery in the extension.
